// Generated by gencpp from file tugas4/Phytagoras.msg
// DO NOT EDIT!


#ifndef TUGAS4_MESSAGE_PHYTAGORAS_H
#define TUGAS4_MESSAGE_PHYTAGORAS_H

#include <ros/service_traits.h>


#include <tugas4/PhytagorasRequest.h>
#include <tugas4/PhytagorasResponse.h>


namespace tugas4
{

struct Phytagoras
{

typedef PhytagorasRequest Request;
typedef PhytagorasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Phytagoras
} // namespace tugas4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tugas4::Phytagoras > {
  static const char* value()
  {
    return "55d1a215f43fd1f64eb105a505b172c4";
  }

  static const char* value(const ::tugas4::Phytagoras&) { return value(); }
};

template<>
struct DataType< ::tugas4::Phytagoras > {
  static const char* value()
  {
    return "tugas4/Phytagoras";
  }

  static const char* value(const ::tugas4::Phytagoras&) { return value(); }
};


// service_traits::MD5Sum< ::tugas4::PhytagorasRequest> should match
// service_traits::MD5Sum< ::tugas4::Phytagoras >
template<>
struct MD5Sum< ::tugas4::PhytagorasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tugas4::Phytagoras >::value();
  }
  static const char* value(const ::tugas4::PhytagorasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugas4::PhytagorasRequest> should match
// service_traits::DataType< ::tugas4::Phytagoras >
template<>
struct DataType< ::tugas4::PhytagorasRequest>
{
  static const char* value()
  {
    return DataType< ::tugas4::Phytagoras >::value();
  }
  static const char* value(const ::tugas4::PhytagorasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tugas4::PhytagorasResponse> should match
// service_traits::MD5Sum< ::tugas4::Phytagoras >
template<>
struct MD5Sum< ::tugas4::PhytagorasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tugas4::Phytagoras >::value();
  }
  static const char* value(const ::tugas4::PhytagorasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tugas4::PhytagorasResponse> should match
// service_traits::DataType< ::tugas4::Phytagoras >
template<>
struct DataType< ::tugas4::PhytagorasResponse>
{
  static const char* value()
  {
    return DataType< ::tugas4::Phytagoras >::value();
  }
  static const char* value(const ::tugas4::PhytagorasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUGAS4_MESSAGE_PHYTAGORAS_H
